# Generated by Django 5.2 on 2025-05-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('receptionist', 'Receptionist'), ('housekeeping', 'Housekeeping'), ('security', 'Security'), ('maintenance', 'Maintenance')], max_length=50),
        ),
    ]
