# Generated by Django 5.2 on 2025-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_websiteuser_delete_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kategori', models.CharField(choices=[('souvenir', 'Souvenir'), ('addon', 'Room Add-On'), ('wellness', 'Wellness & Spa'), ('food', 'Food & Beverage')], max_length=20)),
                ('tersedia', models.BooleanField(default=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/')),
            ],
        ),
    ]
