# Generated by Django 5.2 on 2025-06-04 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reservation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_booking', models.DateTimeField(blank=True, null=True)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.websiteuser')),
            ],
        ),
    ]
