# Generated by Django 5.2 on 2025-06-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='reservasi',
        ),
        migrations.AddField(
            model_name='productorder',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.websiteuser'),
            preserve_default=False,
        ),
    ]
