# Generated by Django 5.2 on 2025-06-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('subject', models.CharField(choices=[('room_inquiry', 'Room Inquiry'), ('booking_issue', 'Booking Issue'), ('payment_question', 'Payment Question'), ('service_request', 'Service Request'), ('feedback', 'Feedback / Suggestions'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.websiteuser')),
            ],
        ),
    ]
