# Generated by Django 5.2 on 2025-06-16 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='guest',
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.websiteuser'),
        ),
    ]
