# Generated by Django 5.2 on 2025-06-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_feedback_guest_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('occupied_rooms', models.PositiveIntegerField()),
                ('available_rooms', models.PositiveIntegerField()),
                ('maintenance_rooms', models.PositiveIntegerField()),
                ('occupancy_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
